/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventschedulingsystem;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author alfin
 */

public class AaLogin extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
        static final String DB_URL="jdbc:mysql://localhost:3306/EventSS"; 
	static final String USER ="root";
	static final String PASS = "Aleena123$";
    public AaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LSignup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 36, 51));

        jPanel3.setBackground(new java.awt.Color(13, 36, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("USERNAME");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 140, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASSWORD");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 140, -1));

        jLabel10.setText("jLabel5");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 361, 2));

        tUsername.setBackground(new java.awt.Color(13, 36, 51));
        tUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tUsername.setForeground(new java.awt.Color(255, 255, 255));
        tUsername.setBorder(null);
        tUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsernameActionPerformed(evt);
            }
        });
        jPanel3.add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 361, 30));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 361, -1));

        tPassword.setBackground(new java.awt.Color(13, 36, 51));
        tPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tPassword.setForeground(new java.awt.Color(255, 255, 255));
        tPassword.setBorder(null);
        jPanel3.add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 361, -1));

        btnLogin.setBackground(new java.awt.Color(240, 151, 57));
        btnLogin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 361, 50));

        jPanel5.setBackground(new java.awt.Color(240, 151, 57));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_150px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 880));

        LSignup.setBackground(new java.awt.Color(13, 36, 51));
        LSignup.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        LSignup.setForeground(new java.awt.Color(255, 255, 255));
        LSignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LSignup.setText("Don't Have Account");
        LSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LSignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LSignupMouseExited(evt);
            }
        });
        jPanel3.add(LSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 150, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 876));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsernameActionPerformed

    private void LSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSignupMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_LSignupMouseEntered

    private void LSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSignupMouseExited
        // TODO add your handling code here:
        LSignup.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_LSignupMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       // TODO add your handling code here:
       try{
           //open connection
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection(DB_URL,USER,PASS);
           //accept user and pass
           String username =tUsername.getText();
           String password =tPassword.getText();
           
           Statement st= con.createStatement();
           
           //mysql query
           
           String sql="select * from login where username='"+username+"' and password='"+password+"'";
           ResultSet rs= st.executeQuery(sql);
           
           
           if(rs.next()){
               //if username and pass is true then go to home
               String adminValue = rs.getString("admin"); // Retrieve the value of "admin" column

            if (adminValue.equals("YES")) {
                // Admin user
                dispose(); // Close login
                AdminDash ad = new AdminDash();
                ad.show();
            } else if (adminValue.equals("NO")) {
                // HOD user
                dispose(); // Close login
                HodDash hod = new HodDash();
                hod.show();
            } else {
                // Invalid admin value
                JOptionPane.showMessageDialog(this, "Invalid admin value in the database.");
            }
               
           }else{
               //if user and pass is wrong
               JOptionPane.showMessageDialog(this,"username or password is wrong..");
               tUsername.setText("");
               tPassword.setText("");
           }
           
           
       }catch(Exception e){
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void LSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSignupMouseClicked
        // TODO add your handling code here:
        dispose();
       SignUp s=new SignUp();
       s.setTitle("Register a User");
       s.setVisible(true);
    }//GEN-LAST:event_LSignupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LSignup;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
