/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package eventschedulingsystem;

import static eventschedulingsystem.Events.DB_URL;
import static eventschedulingsystem.Events.PASS;
import static eventschedulingsystem.Events.USER;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfin
 */
public class view extends javax.swing.JInternalFrame {

    /**
     * Creates new form Events
     */
        static final String DB_URL="jdbc:mysql://localhost:3306/EventSS"; 
	static final String USER ="root";
	static final String PASS = "Aleena123$";
    public view() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        displayEventData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(850, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 25)); // NOI18N
        jLabel1.setText("VIEW CREATED EVENT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EVENT NAME", "EVENT DATE", "START TIME", "STOP TIME", "AM/PM", "HALLS ALLOCATED"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(291, 291, 291))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(512, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void displayEventData() {
        // Create a connection to your database
        try (Connection connection =DriverManager.getConnection(DB_URL,USER,PASS);) {
            // Create a statement for executing SQL queries
            Statement statement = connection.createStatement();
            
            // Execute a query to retrieve event data
            ResultSet resultSet = statement.executeQuery("SELECT * FROM hallallocation");
            
            // Create a DefaultTableModel to hold the table data
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            
            // Clear the existing table data
            tableModel.setRowCount(0);
            
            // Iterate over the query results and populate the table model
            while (resultSet.next()) {
                String eventName = resultSet.getString("name");
                String eventDate = resultSet.getString("date");
                String startTime = resultSet.getString("start_time");
                String stopTime = resultSet.getString("end_time");
                String amPm = resultSet.getString("am_pm");
                String hallallocated= resultSet.getString("hallallocate");
                // Add a new row to the table model with the retrieved data
                tableModel.addRow(new Object[]{eventName, eventDate, startTime, stopTime, amPm, hallallocated});
            }
            
            // Close the ResultSet, statement, and connection
            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle any errors that may occur during the database operations
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
